[tool.isort]
src_paths = [
    "evaluation",
    "log",
    "models",
    "pretraining",
]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-v"
markers = [
    "slow: mark test as slow.",
]
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 80
