[tool.pytest.ini_options]
addopts = "-v"
markers = [
    "slow: mark test as slow.",
]
testpaths = [
    "tests",
]

[tool.isort]
src_paths = [
    "evaluation",
    "log",
    "models",
    "pretraining",
]
