[tool.isort]
src_paths = [
    "src",
    "utils",
]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = [ # Note that this only excludes discovery when using mypy from cli
    "tests",
]

[tool.pytest.ini_options]
addopts = "-v"
markers = [
    "slow: mark test as slow.",
]
testpaths = [
    "tests",
]
tmp_path_retention_policy = "none"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "D",
]
ignore = [
    "D202",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
